version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker-v2/Dockerfile
    ports:
      - "8089:80"
    volumes:
      - ../chat-client:/var/www/html
    depends_on:
      - db
      - websocket
    environment:
      - DB_HOST=db
      - DB_USER=hnschat
      - DB_PASSWORD=hnschat-password
      - DB_NAME=hnschat
      - WS_HOST=websocket
      - WS_PORT=8080

  websocket:
    build:
      context: ..
      dockerfile: docker-v2/Dockerfile.server
    ports:
      - "8080:8080"
    volumes:
      - ../chat-server:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=hnschat
      - DB_PASSWORD=hnschat-password
      - DB_NAME=hnschat

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=hnschat
      - MYSQL_USER=hnschat
      - MYSQL_PASSWORD=hnschat-password
    volumes:
      - mysql_data:/var/lib/mysql
      - ../chat-server/hnschat.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: 